# Generated by Django 5.0.6 on 2024-07-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='shipping_address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='shipping_email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='fullname',
            new_name='shipping_fullname',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalcode',
            new_name='shipping_postalcode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='region',
            new_name='shipping_region',
        ),
    ]
